-- MySQL Script generated by MySQL Workbench
-- Fri Jan 3 02:27:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gacha_game
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gacha_game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gacha_game` DEFAULT CHARACTER SET utf8 ;
USE `gacha_game` ;

-- -----------------------------------------------------
-- Table `gacha_game`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gacha_game`.`user` (
  `user_id` VARCHAR(128) NOT NULL COMMENT 'ユーザID',
  `auth_token` VARCHAR(128) NOT NULL COMMENT '認証トークン',
  `name` VARCHAR(64) NOT NULL COMMENT 'ユーザ名',
  PRIMARY KEY (`user_id`),
  INDEX `idx_authToken` (`auth_token` ASC))
ENGINE = InnoDB
COMMENT = 'ユーザ';


-- -----------------------------------------------------
-- Table `gacha_game`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gacha_game`.`characters` (
  `character_id` VARCHAR(128) NOT NULL COMMENT 'キャラクターID',
  `name` VARCHAR(64) NOT NULL COMMENT 'キャラクター名',
  `power` INT UNSIGNED NOT NULL COMMENT 'パワー'
  `type` INT UNSIGNED NOT NULL COMMENT 'type'
  PRIMARY KEY (`character_id`))
ENGINE = InnoDB
COMMENT = 'キャラクター';


-- -----------------------------------------------------
-- Table `gacha_game`.`user_characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gacha_game`.`user_characters` (
  `user_id` VARCHAR(128) NOT NULL COMMENT 'ユーザID',
  `user_character_id` VARCHAR(128) NOT NULL COMMENT 'ユーザ名',
  `character_id` VARCHAR(128) NOT NULL COMMENT 'キャラクターID',
  PRIMARY KEY (`user_id`, `user_character_id`),
  INDEX `fk_user_character_user_idx` (`user_id` ASC),
  INDEX `fk_user_character_character_idx` (`character_id` ASC),
  CONSTRAINT `fk_user_characters_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gacha_game`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_characters_characters`
    FOREIGN KEY (`character_id`)
    REFERENCES `gacha_game`.`characters` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ユーザ所持キャラクター';


-- -----------------------------------------------------
-- Table `gacha_game`.`gacha_odds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gacha_game`.`gacha_odds` (
  `character_id` VARCHAR(128) NOT NULL COMMENT 'キャラクターID',
  `odds` INT NOT NULL COMMENT '排出重み',
  INDEX `fk_gacha_odds_character_idx` (`character_id` ASC),
  PRIMARY KEY (`character_id`),
  CONSTRAINT `fk_gacha_odds_characters`
    FOREIGN KEY (`character_id`)
    REFERENCES `gacha_game`.`characters` (`character_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'ガチャ排出情報';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
